config/routes.rb
Rails.application.routes.draw do
  root to: "sites#root"
  post "login" => "sessions#create"
  delete "sessions" => "sessions#destroy"
  post "signup" => "users#create"
  post "addtocart" => "carts#add_to_cart"
  post "removefromcart" => "carts#remove_from_cart"
  resources :sessions, only: [:create, :new, :destroy]
  resources :users, only: [:show, :create, :new]
  resources :products, only: [:index, :show]
  resources :carts, only: [:show, :add_to_cart, :remove_from_cart]
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	validates :user_id, presence: true

	belongs_to :user
	has_many :cart_items
	has_many :products, through: :cart_items

	def add_item(product_id)
		cart_item = CartItem.new({
				cart_id: self.id,
				product_id: product_id
			})
		cart_item.save!
	end

	def remove_item(product_id)
		cart_item = CartItem.find_by({
					cart_id: self.id,
					product_id: product_id
				})
		cart_item.destroy!
	end
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
	validates :cart_id, :product_id, presence: true

	belongs_to :cart
	belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :name, :brand, :model, :price, :desc, :sku, presence: true

	has_many :cart_items
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :username, :session_token, :password_digest, :email, presence: true
	validates :password, length: { minimum: 6, allow_nil: true }
	validates :username, :email, uniqueness: true

	has_one :cart
	has_many :products, through: :cart

	attr_reader :password
	after_initialize :ensure_session_token
	after_create :create_cart

	def self.find_by_credentials(username, password)
		user = User.find_by_username(username)
		return nil unless user && user.is_password?(password)
		user
	end

	def reset_session_token
		self.session_token = User.generate_session_token
		self.save!
		self.session_token
	end

	def ensure_session_token
		self.session_token ||= User.generate_session_token
	end

	def self.generate_session_token
		SecureRandom.urlsafe_base64
	end

	def password=(password)
		@password = password
		self.password_digest = BCrypt::Password.create(password)
	end

	def is_password?(password)
		BCrypt::Password.new(self.password_digest).is_password?(password)
	end

	def create_cart
		self.cart = Cart.new({user_id: self.id})
		begin
			self.cart.save!
		rescue => e
			p "***create_cart***"
			p e.message
			p e.backtrace
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :check_logged_in

  def current_user
  	return nil if session[:token].nil?
  	@current_user ||= User.includes(:cart).find_by(session_token: session[:token])
  end

  def log_in(user)
  	session[:token] = user.reset_session_token
  end

  def log_out
  	current_user.reset_session_token!
  	session[:token] = nil
  end

  def check_logged_in
    unless current_user
      redirect_to root_url
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	skip_before_action :validate_current_user, only: [:add_to_cart]
	before_action :check_logged_in
	
	def show
		@cart = Cart.includes(cart_items: :product).find(params[:id])
	end

	def add_to_cart
		cart_id = current_user.cart.id
		product_id = params[:product_id]
		begin
			current_user.cart.add_item(product_id)
			redirect_to cart_path(cart_id)
		rescue => e
			p "***add_to_cart***"
			p e.message
			p e.backtrace
		end
	end

	def remove_from_cart
		cart_id = current_user.cart.id
		product_id = params[:product_id]
		begin
			current_user.cart.remove_item(product_id)
			redirect_to cart_path(cart_id)
		rescue => e
			p "***remove_from_cart***"
			p e.message
			p e.backtrace
		end
	end

	private
	def validate_current_user
		unless current_user.id == params[:id].to_i
			flash[:error] = "You don't have access to that"
			redirect_to cart_path(current_user.id)
		end
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.all
	end

	def show
		@product = Product.find(params[:id])
		render json: @product
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		user = User.find_by_credentials(
				params[:user][:username],
				params[:user][:password]
			)

		if user.nil?
			flash.now[:errors] = login_errors(params[:user])
			p flash.now[:errors]
			render :new, status: 422
		else
			log_in(user)
			redirect_to user_path(user.id)
		end
	end

	def destroy
		log_out
		redirect_to root_url
	end

	private
	def login_errors(user_params)
		errors = []
		user_params.each do |key, val|
			next unless ["username", "password"].rindex(key)
			
			if val.blank?
				errors << "#{key.capitalize} can't be blank"
			elsif key == "username" && val.present?
				if User.exists?({username: val})
					user = User.find_by({username: val})
					errors << "Password is invalid" if user.is_password?(user_params[:password])
				else
					errors << "Username is invalid"
				end
			end
		end

		errors
	end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
	def root
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	wrap_parameters false

	def show
		@user = User.includes(:cart).find(params[:id])
	end

	def create
		@user = User.new(user_params)

		if @user.save
			log_in(@user)
			redirect_to user_path(@user.id)
		else
			flash.now[:errors] = @user.errors.full_messages
			render :new, status: 422
		end
	end

	private

	def user_params
		uparams = params.require(:user).permit(:username, :email, :password)
		uparams.delete(:password) if uparams[:password].blank?
		uparams
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	include ProductHelper
	
	def username(user)
		user.username if user && user.username.present?
	end

	def display_error(type, errors)
		"<span class='errors #{type}'>
			<span class='arrow'></span>
			#{errors.select {|error| error.downcase.match(type)}[0]}
		</span>".html_safe if type && errors && !errors.select {|error| error.downcase.match(type)}.empty?
	end
end

app/helpers/product_helper.rb
module ProductHelper
	def id(product)
		product.id if product && product.id.present?
	end

	def name_and_model(product)
		if product && product.name.present? && product.model.present?
			"#{product.name} <i>#{product.model}</i>".html_safe
		end
	end

	def brand(product)
		product.brand if product && product.brand.present?
	end

	def name(product)
		product.name if product && product.name.present?
	end

	def model(product)
		product.model if product && product.model.present?
	end

	def sku(product)
		product.sku if product && product.sku.present?
	end

	def price(product)
		"$#{product.price}" if product && product.price.present?
	end

	def desc(product)
		product.desc if product && product.desc.present?
	end
end

app/views/carts/show.html.erb
<div class="cart">
	<h1>Your Cart</h1>

	<% if @cart.cart_items.empty? %>
		<h2>Cart is empty <a href="/products">Go buy something!</a></h2>
	<% else %>
		<div class="row grid">
			<% @cart.cart_items.each do |cart_item| %>
				<% product = cart_item.product %>
				<div class="item large-4 small-6 columns">
					<form action="/removefromcart" method="post">
						<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
						<input type="hidden" name="product_id" value="<%= product.id %>">
						<button class="remove-cart" type="submit">
							<a href="javascript:void(0)" title="Remove from Cart">
								<i class="fa fa-times"></i>
							</a>
						</button>
					</form>
					<div class="panel">
						<div class="brand"><%= brand(product) %></div>
						<div class="name"><%= name_and_model(product) %></div>
						<div class="sku">SKU: <%= sku(product) %></div>
						<div class="price"><%= price(product) %></div>
						<div class="desc"><%= desc(product) %></div>
					</div>
				</div>
			<% end %>
		</div>
	<% end %>
</div>

app/views/layouts/_header.html.erb
<header>
	<div class="menu">
		<span class="menuicon" onclick="menuToggle()">
			<div class="top">
				<div class="bar"></div>
				<div class="bar"></div>
			</div>
			<div class="mid"></div>
			<div class="bot">
				<div class="bar"></div>
				<div class="bar"></div>
			</div>
		</span>
		<% if current_user %>
			<h3 class="greeting">Welcome, <a href="/users/<%= current_user.id %>"><%= username(current_user) %></a>
			</h3>
		<% end %>
		<ul class="dropdown">
			<li><a href="/products"><i class="fa fa-product-hunt"></i> Products</a></li>
			<% if current_user %>
				<li><a href="/carts/<%= current_user.cart.id %>"><i class="fa fa-shopping-cart"></i> Cart</a></li>
				<li><a href="javascript:void(0)"><i class="fa fa-sign-out"></i> <%= button_to "Sign Out", sessions_url, method: :delete %></a></li>
			<% else %>
				<li><a href="/"><i class="fa fa-sign-in"></i> Sign In</a></li>
			<% end %>
		</ul>
	</div>
	<div class="sessions">
		<% if current_user %>
			<%= button_to "Sign Out", sessions_url, method: :delete %>
		<% end %>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Celmatix Test" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render "layouts/header" %>
    <div class="main">
      <%= yield %>
    </div>

  </body>
</html>

app/views/products/index.html.erb
<div class="products">
	<h1>Products</h1>
	<div class="row grid">
		<% @products.each do |product| %>
			<div class="item large-4 small-6 columns" data-id="<%= product.id %>" onclick="productModalToggle(this, event)">
				<div class="panel" data-id="<%= id(product) %>">
					<div class="brand"><%= brand(product) %></div>
					<div class="name"><%= name_and_model(product) %></div>
					<div class="price"><%= price(product) %></div>
				</div>
			</div>
		<% end %>
	</div>
	<div class="product-modal modal hidden">
		<div class="content">
			<i class="fa fa-times close" onclick="closeModal(this)"></i>
			<div class="brand"></div>
			<div class="name"><div class="model"></div></div>
			<div class="price"></div>
			<div class="desc"></div>
			<form action="/addtocart" method="post">
				<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
				<input type="hidden" name="product_id" value="">
				<button class="add-cart" type="submit">
					<a href="javascript:void(0)" title="Add to Cart">
						<i class="fa fa-shopping-cart"></i>
					</a>
				</button>
			</form>
		</div>
	</div>
</div>

app/views/sites/root.html.erb
<div id="landing" class="big-nav">
		<a href="/sessions/new"><span>Sign In</span></a>
		<a href="/users/new"><span>Sign Up</span></a>
</div>

app/views/users/_form.html.erb
<form class="sign-in" action="/signup" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label class="username">Username
	  <input class="username" type="text" name="user[username]" value="">
	  <%= display_error("username", flash.now[:errors]) %>
  </label>

  <label class="email">Email
		<input class="email" type="text" name="user[email]" value="">
		<%= display_error("email", flash.now[:errors]) %>
  </label>

  <label class="password">Password
	  <input class="password" type="password" name="user[password]" value="">
	  <%= display_error("password", flash.now[:errors]) %>
  </label>

  <button name="button" class="submit">Sign Up</button>
</form>

app/views/users/new.html.erb
<div class="signup">
	<%= render "form" %>
</div>

app/views/users/show.html.erb
<div class="profile big-nav">
	<a href="/products"><span>View Products</span></a>
	<a href="/carts/<%= @user.cart.id %>"><span>View Cart</span></a>
</div>